name: flutterpad
description: Exploring light-weight pairing between a phone and a dev environment.

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  firebase: ^0.6.0
  flutter:
    path: ../../projects/flutter/flutter/packages/flutter
  markdown: ^0.9.0

dev_dependencies:
  grinder: ^0.8.0

transformers:
- dart_to_js_script_rewriter
